/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountStats extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.AccountStatsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 794320538;

	/**
	 * The reference instance of <code>Account.accountStats</code>
	 */
	public static final com.houzicore.shared.database.tables.AccountStats accountStats = new com.houzicore.shared.database.tables.AccountStats();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.AccountStatsRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.AccountStatsRecord.class;
	}

	/**
	 * The column <code>Account.accountStats.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountStatsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountStats.accountId</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountStatsRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountStats.statId</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountStatsRecord, java.lang.Integer> statId = createField("statId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountStats.value</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountStatsRecord, java.lang.Integer> value = createField("value", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>Account.accountStats</code> table reference
	 */
	public AccountStats() {
		this("accountStats", null);
	}

	/**
	 * Create an aliased <code>Account.accountStats</code> table reference
	 */
	public AccountStats(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.AccountStats.accountStats);
	}

	private AccountStats(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.AccountStatsRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountStats(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.AccountStatsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.AccountStatsRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_accountStats;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountStatsRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_accountStats_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountStatsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountStatsRecord>>asList(com.houzicore.shared.database.Keys.KEY_accountStats_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.AccountStatsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.AccountStatsRecord, ?>>asList(com.houzicore.shared.database.Keys.accountStats_ibfk_1, com.houzicore.shared.database.Keys.accountStats_ibfk_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.AccountStats as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.AccountStats(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.AccountStats rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.AccountStats(name, null);
	}
}
