/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountTasks extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.AccountTasksRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1258627706;

	/**
	 * The reference instance of <code>Account.accountTasks</code>
	 */
	public static final com.houzicore.shared.database.tables.AccountTasks accountTasks = new com.houzicore.shared.database.tables.AccountTasks();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.AccountTasksRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.AccountTasksRecord.class;
	}

	/**
	 * The column <code>Account.accountTasks.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountTasksRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountTasks.accountId</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountTasksRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountTasks.taskId</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountTasksRecord, java.lang.Integer> taskId = createField("taskId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>Account.accountTasks</code> table reference
	 */
	public AccountTasks() {
		this("accountTasks", null);
	}

	/**
	 * Create an aliased <code>Account.accountTasks</code> table reference
	 */
	public AccountTasks(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.AccountTasks.accountTasks);
	}

	private AccountTasks(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.AccountTasksRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountTasks(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.AccountTasksRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.AccountTasksRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_accountTasks;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountTasksRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_accountTasks_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountTasksRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountTasksRecord>>asList(com.houzicore.shared.database.Keys.KEY_accountTasks_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.AccountTasksRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.AccountTasksRecord, ?>>asList(com.houzicore.shared.database.Keys.ACCOUNTTASKS_ACCOUNTID, com.houzicore.shared.database.Keys.ACCOUNTTASKS_TASKID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.AccountTasks as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.AccountTasks(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.AccountTasks rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.AccountTasks(name, null);
	}
}
