/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountCoinTransactions extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.AccountCoinTransactionsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -205501041;

	/**
	 * The reference instance of <code>Account.accountCoinTransactions</code>
	 */
	public static final com.houzicore.shared.database.tables.AccountCoinTransactions accountCoinTransactions = new com.houzicore.shared.database.tables.AccountCoinTransactions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.AccountCoinTransactionsRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.AccountCoinTransactionsRecord.class;
	}

	/**
	 * The column <code>Account.accountCoinTransactions.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountCoinTransactionsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountCoinTransactions.accountId</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountCoinTransactionsRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountCoinTransactions.reason</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountCoinTransactionsRecord, java.lang.String> reason = createField("reason", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>Account.accountCoinTransactions.coins</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountCoinTransactionsRecord, java.lang.Integer> coins = createField("coins", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>Account.accountCoinTransactions</code> table reference
	 */
	public AccountCoinTransactions() {
		this("accountCoinTransactions", null);
	}

	/**
	 * Create an aliased <code>Account.accountCoinTransactions</code> table reference
	 */
	public AccountCoinTransactions(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.AccountCoinTransactions.accountCoinTransactions);
	}

	private AccountCoinTransactions(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.AccountCoinTransactionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountCoinTransactions(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.AccountCoinTransactionsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.AccountCoinTransactionsRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_accountCoinTransactions;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountCoinTransactionsRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_accountCoinTransactions_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountCoinTransactionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountCoinTransactionsRecord>>asList(com.houzicore.shared.database.Keys.KEY_accountCoinTransactions_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.AccountCoinTransactionsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.AccountCoinTransactionsRecord, ?>>asList(com.houzicore.shared.database.Keys.FK_ACT_ACCOUNTS_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.AccountCoinTransactions as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.AccountCoinTransactions(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.AccountCoinTransactions rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.AccountCoinTransactions(name, null);
	}
}
