/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountIgnore extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.AccountIgnoreRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -191436863;

	/**
	 * The reference instance of <code>Account.accountIgnore</code>
	 */
	public static final com.houzicore.shared.database.tables.AccountIgnore accountIgnore = new com.houzicore.shared.database.tables.AccountIgnore();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.AccountIgnoreRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.AccountIgnoreRecord.class;
	}

	/**
	 * The column <code>Account.accountIgnore.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountIgnoreRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountIgnore.uuidIgnorer</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountIgnoreRecord, java.lang.String> uuidIgnorer = createField("uuidIgnorer", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>Account.accountIgnore.uuidIgnored</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountIgnoreRecord, java.lang.String> uuidIgnored = createField("uuidIgnored", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>Account.accountIgnore</code> table reference
	 */
	public AccountIgnore() {
		this("accountIgnore", null);
	}

	/**
	 * Create an aliased <code>Account.accountIgnore</code> table reference
	 */
	public AccountIgnore(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.AccountIgnore.accountIgnore);
	}

	private AccountIgnore(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.AccountIgnoreRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountIgnore(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.AccountIgnoreRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.AccountIgnoreRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_accountIgnore;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountIgnoreRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_accountIgnore_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountIgnoreRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountIgnoreRecord>>asList(com.houzicore.shared.database.Keys.KEY_accountIgnore_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.AccountIgnore as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.AccountIgnore(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.AccountIgnore rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.AccountIgnore(name, null);
	}
}
