/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountInventory extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.AccountInventoryRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 1899953592;

	/**
	 * The reference instance of <code>Account.accountInventory</code>
	 */
	public static final com.houzicore.shared.database.tables.AccountInventory accountInventory = new com.houzicore.shared.database.tables.AccountInventory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.AccountInventoryRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.AccountInventoryRecord.class;
	}

	/**
	 * The column <code>Account.accountInventory.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountInventoryRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountInventory.accountId</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountInventoryRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountInventory.itemId</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountInventoryRecord, java.lang.Integer> itemId = createField("itemId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountInventory.count</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountInventoryRecord, java.lang.Integer> count = createField("count", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>Account.accountInventory</code> table reference
	 */
	public AccountInventory() {
		this("accountInventory", null);
	}

	/**
	 * Create an aliased <code>Account.accountInventory</code> table reference
	 */
	public AccountInventory(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.AccountInventory.accountInventory);
	}

	private AccountInventory(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.AccountInventoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountInventory(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.AccountInventoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.AccountInventoryRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_accountInventory;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountInventoryRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_accountInventory_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountInventoryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountInventoryRecord>>asList(com.houzicore.shared.database.Keys.KEY_accountInventory_PRIMARY, com.houzicore.shared.database.Keys.KEY_accountInventory_accountItemIndex);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.AccountInventoryRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.AccountInventoryRecord, ?>>asList(com.houzicore.shared.database.Keys.accountInventory_ibfk_1, com.houzicore.shared.database.Keys.accountInventory_ibfk_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.AccountInventory as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.AccountInventory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.AccountInventory rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.AccountInventory(name, null);
	}
}
