/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountEssenceTransactions extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.AccountEssenceTransactionsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1280518241;

	public static final com.houzicore.shared.database.tables.AccountEssenceTransactions accountEssenceTransactions = new com.houzicore.shared.database.tables.AccountEssenceTransactions();

	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.AccountEssenceTransactionsRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.AccountEssenceTransactionsRecord.class;
	}

	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountEssenceTransactionsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountEssenceTransactionsRecord, java.lang.String> accounts_uuid = createField("accounts_uuid", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountEssenceTransactionsRecord, java.lang.String> reason = createField("reason", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountEssenceTransactionsRecord, java.lang.Integer> essence = createField("essence", org.jooq.impl.SQLDataType.INTEGER, this, "");

	public AccountEssenceTransactions() {
		this("accountEssenceTransactions", null);
	}

	public AccountEssenceTransactions(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.AccountEssenceTransactions.accountEssenceTransactions);
	}

	private AccountEssenceTransactions(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.AccountEssenceTransactionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountEssenceTransactions(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.AccountEssenceTransactionsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.AccountEssenceTransactionsRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_accountEssenceTransactions;
	}

	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountEssenceTransactionsRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_accountEssenceTransactions_PRIMARY;
	}

	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountEssenceTransactionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountEssenceTransactionsRecord>>asList(com.houzicore.shared.database.Keys.KEY_accountEssenceTransactions_PRIMARY);
	}

	@Override
	public java.util.List<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.AccountEssenceTransactionsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.AccountEssenceTransactionsRecord, ?>>asList(com.houzicore.shared.database.Keys.accountEssenceTransactions_ibfk_1);
	}

	@Override
	public com.houzicore.shared.database.tables.AccountEssenceTransactions as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.AccountEssenceTransactions(alias, this);
	}

	public com.houzicore.shared.database.tables.AccountEssenceTransactions rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.AccountEssenceTransactions(name, null);
	}
}
