/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountClan extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.AccountClanRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 1838492867;

	/**
	 * The reference instance of <code>Account.accountClan</code>
	 */
	public static final com.houzicore.shared.database.tables.AccountClan accountClan = new com.houzicore.shared.database.tables.AccountClan();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.AccountClanRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.AccountClanRecord.class;
	}

	/**
	 * The column <code>Account.accountClan.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountClanRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountClan.accountId</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountClanRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountClan.clanId</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountClanRecord, java.lang.Integer> clanId = createField("clanId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountClan.clanRole</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.AccountClanRecord, java.lang.String> clanRole = createField("clanRole", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * Create a <code>Account.accountClan</code> table reference
	 */
	public AccountClan() {
		this("accountClan", null);
	}

	/**
	 * Create an aliased <code>Account.accountClan</code> table reference
	 */
	public AccountClan(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.AccountClan.accountClan);
	}

	private AccountClan(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.AccountClanRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountClan(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.AccountClanRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.AccountClanRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_accountClan;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountClanRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_accountClan_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountClanRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.AccountClanRecord>>asList(com.houzicore.shared.database.Keys.KEY_accountClan_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.AccountClanRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.AccountClanRecord, ?>>asList(com.houzicore.shared.database.Keys.FK_accountClan_accounts, com.houzicore.shared.database.Keys.FK_accountClan_clans2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.AccountClan as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.AccountClan(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.AccountClan rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.AccountClan(name, null);
	}
}
