/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bonus extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.BonusRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -70389593;

	/**
	 * The reference instance of <code>Account.bonus</code>
	 */
	public static final com.houzicore.shared.database.tables.Bonus bonus = new com.houzicore.shared.database.tables.Bonus();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.BonusRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.BonusRecord.class;
	}

	/**
	 * The column <code>Account.bonus.accountId</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.BonusRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.bonus.dailytime</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.BonusRecord, java.sql.Timestamp> dailytime = createField("dailytime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>Account.bonus.ranktime</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.BonusRecord, java.sql.Date> ranktime = createField("ranktime", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * Create a <code>Account.bonus</code> table reference
	 */
	public Bonus() {
		this("bonus", null);
	}

	/**
	 * Create an aliased <code>Account.bonus</code> table reference
	 */
	public Bonus(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.Bonus.bonus);
	}

	private Bonus(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.BonusRecord> aliased) {
		this(alias, aliased, null);
	}

	private Bonus(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.BonusRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.BonusRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_bonus;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.BonusRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_bonus_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.BonusRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.BonusRecord>>asList(com.houzicore.shared.database.Keys.KEY_bonus_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.BonusRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.BonusRecord, ?>>asList(com.houzicore.shared.database.Keys.bonus_ibfk_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.Bonus as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.Bonus(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.Bonus rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.Bonus(name, null);
	}
}
