/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClanServer extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.ClanServerRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -566894974;

	/**
	 * The reference instance of <code>Account.clanServer</code>
	 */
	public static final com.houzicore.shared.database.tables.ClanServer clanServer = new com.houzicore.shared.database.tables.ClanServer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.ClanServerRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.ClanServerRecord.class;
	}

	/**
	 * The column <code>Account.clanServer.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ClanServerRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clanServer.serverName</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ClanServerRecord, java.lang.String> serverName = createField("serverName", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>Account.clanServer</code> table reference
	 */
	public ClanServer() {
		this("clanServer", null);
	}

	/**
	 * Create an aliased <code>Account.clanServer</code> table reference
	 */
	public ClanServer(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.ClanServer.clanServer);
	}

	private ClanServer(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.ClanServerRecord> aliased) {
		this(alias, aliased, null);
	}

	private ClanServer(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.ClanServerRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.ClanServerRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_clanServer;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.ClanServerRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_clanServer_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.ClanServerRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.ClanServerRecord>>asList(com.houzicore.shared.database.Keys.KEY_clanServer_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.ClanServer as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.ClanServer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.ClanServer rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.ClanServer(name, null);
	}
}
