/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClanAlliances extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.ClanAlliancesRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 2034100059;

	/**
	 * The reference instance of <code>Account.clanAlliances</code>
	 */
	public static final com.houzicore.shared.database.tables.ClanAlliances clanAlliances = new com.houzicore.shared.database.tables.ClanAlliances();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.ClanAlliancesRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.ClanAlliancesRecord.class;
	}

	/**
	 * The column <code>Account.clanAlliances.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ClanAlliancesRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clanAlliances.clanId</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ClanAlliancesRecord, java.lang.Integer> clanId = createField("clanId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Account.clanAlliances.otherClanId</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ClanAlliancesRecord, java.lang.Integer> otherClanId = createField("otherClanId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Account.clanAlliances.trusted</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ClanAlliancesRecord, java.lang.Boolean> trusted = createField("trusted", org.jooq.impl.SQLDataType.BIT, this, "");

	/**
	 * Create a <code>Account.clanAlliances</code> table reference
	 */
	public ClanAlliances() {
		this("clanAlliances", null);
	}

	/**
	 * Create an aliased <code>Account.clanAlliances</code> table reference
	 */
	public ClanAlliances(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.ClanAlliances.clanAlliances);
	}

	private ClanAlliances(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.ClanAlliancesRecord> aliased) {
		this(alias, aliased, null);
	}

	private ClanAlliances(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.ClanAlliancesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.ClanAlliancesRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_clanAlliances;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.ClanAlliancesRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_clanAlliances_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.ClanAlliancesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.ClanAlliancesRecord>>asList(com.houzicore.shared.database.Keys.KEY_clanAlliances_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.ClanAlliancesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.ClanAlliancesRecord, ?>>asList(com.houzicore.shared.database.Keys.clanAlliances_ibfk_2, com.houzicore.shared.database.Keys.clanAlliances_ibfk_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.ClanAlliances as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.ClanAlliances(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.ClanAlliances rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.ClanAlliances(name, null);
	}
}
