/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClanTerritory extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.ClanTerritoryRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1393369389;

	/**
	 * The reference instance of <code>Account.clanTerritory</code>
	 */
	public static final com.houzicore.shared.database.tables.ClanTerritory clanTerritory = new com.houzicore.shared.database.tables.ClanTerritory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.ClanTerritoryRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.ClanTerritoryRecord.class;
	}

	/**
	 * The column <code>Account.clanTerritory.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ClanTerritoryRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clanTerritory.clanId</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ClanTerritoryRecord, java.lang.Integer> clanId = createField("clanId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Account.clanTerritory.serverId</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ClanTerritoryRecord, java.lang.Integer> serverId = createField("serverId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Account.clanTerritory.chunk</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ClanTerritoryRecord, java.lang.String> chunk = createField("chunk", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>Account.clanTerritory.safe</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ClanTerritoryRecord, java.lang.Boolean> safe = createField("safe", org.jooq.impl.SQLDataType.BIT, this, "");

	/**
	 * Create a <code>Account.clanTerritory</code> table reference
	 */
	public ClanTerritory() {
		this("clanTerritory", null);
	}

	/**
	 * Create an aliased <code>Account.clanTerritory</code> table reference
	 */
	public ClanTerritory(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.ClanTerritory.clanTerritory);
	}

	private ClanTerritory(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.ClanTerritoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private ClanTerritory(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.ClanTerritoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.ClanTerritoryRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_clanTerritory;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.ClanTerritoryRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_clanTerritory_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.ClanTerritoryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.ClanTerritoryRecord>>asList(com.houzicore.shared.database.Keys.KEY_clanTerritory_PRIMARY, com.houzicore.shared.database.Keys.KEY_clanTerritory_territory_server_chunk_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.ClanTerritoryRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.ClanTerritoryRecord, ?>>asList(com.houzicore.shared.database.Keys.clanTerritory_ibfk_1, com.houzicore.shared.database.Keys.clanTerritory_ibfk_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.ClanTerritory as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.ClanTerritory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.ClanTerritory rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.ClanTerritory(name, null);
	}
}
