/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EloRating extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.EloRatingRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -747680746;

	/**
	 * The reference instance of <code>Account.eloRating</code>
	 */
	public static final com.houzicore.shared.database.tables.EloRating eloRating = new com.houzicore.shared.database.tables.EloRating();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.EloRatingRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.EloRatingRecord.class;
	}

	/**
	 * The column <code>Account.eloRating.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.EloRatingRecord, org.jooq.types.UInteger> id = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>Account.eloRating.uuid</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.EloRatingRecord, java.lang.String> uuid = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * The column <code>Account.eloRating.gamemode</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.EloRatingRecord, org.jooq.types.UByte> gamemode = createField("gamemode", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>Account.eloRating.matchesPlayed</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.EloRatingRecord, org.jooq.types.UInteger> matchesPlayed = createField("matchesPlayed", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>Account.eloRating.elo</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.EloRatingRecord, java.lang.Integer> elo = createField("elo", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.eloRating.gameType</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.EloRatingRecord, java.lang.String> gameType = createField("gameType", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * Create a <code>Account.eloRating</code> table reference
	 */
	public EloRating() {
		this("eloRating", null);
	}

	/**
	 * Create an aliased <code>Account.eloRating</code> table reference
	 */
	public EloRating(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.EloRating.eloRating);
	}

	private EloRating(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.EloRatingRecord> aliased) {
		this(alias, aliased, null);
	}

	private EloRating(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.EloRatingRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.EloRatingRecord, org.jooq.types.UInteger> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_eloRating;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.EloRatingRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_eloRating_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.EloRatingRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.EloRatingRecord>>asList(com.houzicore.shared.database.Keys.KEY_eloRating_PRIMARY, com.houzicore.shared.database.Keys.KEY_eloRating_uuid_gameType_index);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.EloRating as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.EloRating(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.EloRating rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.EloRating(name, null);
	}
}
