/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FieldOre extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.FieldOreRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -20930501;

	/**
	 * The reference instance of <code>Account.fieldOre</code>
	 */
	public static final com.houzicore.shared.database.tables.FieldOre fieldOre = new com.houzicore.shared.database.tables.FieldOre();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.FieldOreRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.FieldOreRecord.class;
	}

	/**
	 * The column <code>Account.fieldOre.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.FieldOreRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.fieldOre.server</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.FieldOreRecord, java.lang.String> server = createField("server", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>Account.fieldOre.location</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.FieldOreRecord, java.lang.String> location = createField("location", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>Account.fieldOre</code> table reference
	 */
	public FieldOre() {
		this("fieldOre", null);
	}

	/**
	 * Create an aliased <code>Account.fieldOre</code> table reference
	 */
	public FieldOre(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.FieldOre.fieldOre);
	}

	private FieldOre(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.FieldOreRecord> aliased) {
		this(alias, aliased, null);
	}

	private FieldOre(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.FieldOreRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.FieldOreRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_fieldOre;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.FieldOreRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_fieldOre_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.FieldOreRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.FieldOreRecord>>asList(com.houzicore.shared.database.Keys.KEY_fieldOre_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.FieldOre as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.FieldOre(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.FieldOre rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.FieldOre(name, null);
	}
}
