/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemCategories extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.ItemCategoriesRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 1747950682;

	/**
	 * The reference instance of <code>Account.itemCategories</code>
	 */
	public static final com.houzicore.shared.database.tables.ItemCategories itemCategories = new com.houzicore.shared.database.tables.ItemCategories();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.ItemCategoriesRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.ItemCategoriesRecord.class;
	}

	/**
	 * The column <code>Account.itemCategories.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ItemCategoriesRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.itemCategories.name</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ItemCategoriesRecord, java.lang.String> name = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>Account.itemCategories</code> table reference
	 */
	public ItemCategories() {
		this("itemCategories", null);
	}

	/**
	 * Create an aliased <code>Account.itemCategories</code> table reference
	 */
	public ItemCategories(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.ItemCategories.itemCategories);
	}

	private ItemCategories(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.ItemCategoriesRecord> aliased) {
		this(alias, aliased, null);
	}

	private ItemCategories(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.ItemCategoriesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.ItemCategoriesRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_itemCategories;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.ItemCategoriesRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_itemCategories_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.ItemCategoriesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.ItemCategoriesRecord>>asList(com.houzicore.shared.database.Keys.KEY_itemCategories_PRIMARY, com.houzicore.shared.database.Keys.KEY_itemCategories_nameIndex);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.ItemCategories as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.ItemCategories(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.ItemCategories rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.ItemCategories(name, null);
	}
}
