/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mailbox extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.MailboxRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 581316209;

	/**
	 * The reference instance of <code>Account.mailbox</code>
	 */
	public static final com.houzicore.shared.database.tables.Mailbox mailbox = new com.houzicore.shared.database.tables.Mailbox();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.MailboxRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.MailboxRecord.class;
	}

	/**
	 * The column <code>Account.mailbox.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.MailboxRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.mailbox.accountId</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.MailboxRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Account.mailbox.sender</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.MailboxRecord, java.lang.String> sender = createField("sender", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>Account.mailbox.message</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.MailboxRecord, java.lang.String> message = createField("message", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>Account.mailbox.archived</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.MailboxRecord, java.lang.Byte> archived = createField("archived", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * The column <code>Account.mailbox.deleted</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.MailboxRecord, java.lang.Byte> deleted = createField("deleted", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * The column <code>Account.mailbox.timeSent</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.MailboxRecord, java.sql.Timestamp> timeSent = createField("timeSent", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>Account.mailbox</code> table reference
	 */
	public Mailbox() {
		this("mailbox", null);
	}

	/**
	 * Create an aliased <code>Account.mailbox</code> table reference
	 */
	public Mailbox(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.Mailbox.mailbox);
	}

	private Mailbox(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.MailboxRecord> aliased) {
		this(alias, aliased, null);
	}

	private Mailbox(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.MailboxRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.MailboxRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_mailbox;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.MailboxRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_mailbox_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.MailboxRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.MailboxRecord>>asList(com.houzicore.shared.database.Keys.KEY_mailbox_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.MailboxRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.houzicore.shared.database.tables.records.MailboxRecord, ?>>asList(com.houzicore.shared.database.Keys.mailbox_ibfk_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.Mailbox as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.Mailbox(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.Mailbox rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.Mailbox(name, null);
	}
}
