/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerMap extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.PlayerMapRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1399340256;

	/**
	 * The reference instance of <code>Account.playerMap</code>
	 */
	public static final com.houzicore.shared.database.tables.PlayerMap playerMap = new com.houzicore.shared.database.tables.PlayerMap();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.PlayerMapRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.PlayerMapRecord.class;
	}

	/**
	 * The column <code>Account.playerMap.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.PlayerMapRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.playerMap.playerName</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.PlayerMapRecord, java.lang.String> playerName = createField("playerName", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>Account.playerMap.serverName</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.PlayerMapRecord, java.lang.String> serverName = createField("serverName", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>Account.playerMap.us</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.PlayerMapRecord, java.lang.Byte> us = createField("us", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>Account.playerMap</code> table reference
	 */
	public PlayerMap() {
		this("playerMap", null);
	}

	/**
	 * Create an aliased <code>Account.playerMap</code> table reference
	 */
	public PlayerMap(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.PlayerMap.playerMap);
	}

	private PlayerMap(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.PlayerMapRecord> aliased) {
		this(alias, aliased, null);
	}

	private PlayerMap(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.PlayerMapRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.PlayerMapRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_playerMap;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.PlayerMapRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_playerMap_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.PlayerMapRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.PlayerMapRecord>>asList(com.houzicore.shared.database.Keys.KEY_playerMap_PRIMARY, com.houzicore.shared.database.Keys.KEY_playerMap_playerIndex);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.PlayerMap as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.PlayerMap(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.PlayerMap rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.PlayerMap(name, null);
	}
}
