/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServerPassword extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.ServerPasswordRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1801488583;

	/**
	 * The reference instance of <code>Account.serverPassword</code>
	 */
	public static final com.houzicore.shared.database.tables.ServerPassword serverPassword = new com.houzicore.shared.database.tables.ServerPassword();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.ServerPasswordRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.ServerPasswordRecord.class;
	}

	/**
	 * The column <code>Account.serverPassword.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ServerPasswordRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.serverPassword.server</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ServerPasswordRecord, java.lang.String> server = createField("server", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>Account.serverPassword.password</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.ServerPasswordRecord, java.lang.String> password = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>Account.serverPassword</code> table reference
	 */
	public ServerPassword() {
		this("serverPassword", null);
	}

	/**
	 * Create an aliased <code>Account.serverPassword</code> table reference
	 */
	public ServerPassword(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.ServerPassword.serverPassword);
	}

	private ServerPassword(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.ServerPasswordRecord> aliased) {
		this(alias, aliased, null);
	}

	private ServerPassword(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.ServerPasswordRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.ServerPasswordRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_serverPassword;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.ServerPasswordRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_serverPassword_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.ServerPasswordRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.ServerPasswordRecord>>asList(com.houzicore.shared.database.Keys.KEY_serverPassword_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.ServerPassword as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.ServerPassword(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.ServerPassword rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.ServerPassword(name, null);
	}
}
