/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stats extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.StatsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1426984538;

	/**
	 * The reference instance of <code>Account.stats</code>
	 */
	public static final com.houzicore.shared.database.tables.Stats stats = new com.houzicore.shared.database.tables.Stats();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.StatsRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.StatsRecord.class;
	}

	/**
	 * The column <code>Account.stats.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.StatsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.stats.name</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.StatsRecord, java.lang.String> name = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>Account.stats</code> table reference
	 */
	public Stats() {
		this("stats", null);
	}

	/**
	 * Create an aliased <code>Account.stats</code> table reference
	 */
	public Stats(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.Stats.stats);
	}

	private Stats(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.StatsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Stats(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.StatsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.StatsRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_stats;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.StatsRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_stats_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.StatsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.StatsRecord>>asList(com.houzicore.shared.database.Keys.KEY_stats_PRIMARY, com.houzicore.shared.database.Keys.KEY_stats_nameIndex);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.Stats as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.Stats(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.Stats rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.Stats(name, null);
	}
}
