/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * Stores a reference of the various types of statistics and their associated 
 * stat type IDs.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatTypes extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.StatTypesRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -371894741;

	/**
	 * The reference instance of <code>Account.statTypes</code>
	 */
	public static final com.houzicore.shared.database.tables.StatTypes statTypes = new com.houzicore.shared.database.tables.StatTypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.StatTypesRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.StatTypesRecord.class;
	}

	/**
	 * The column <code>Account.statTypes.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.StatTypesRecord, org.jooq.types.UByte> id = createField("id", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>Account.statTypes.name</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.StatTypesRecord, java.lang.String> name = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>Account.statTypes</code> table reference
	 */
	public StatTypes() {
		this("statTypes", null);
	}

	/**
	 * Create an aliased <code>Account.statTypes</code> table reference
	 */
	public StatTypes(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.StatTypes.statTypes);
	}

	private StatTypes(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.StatTypesRecord> aliased) {
		this(alias, aliased, null);
	}

	private StatTypes(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.StatTypesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "Stores a reference of the various types of statistics and their associated stat type IDs.");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.StatTypesRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_statTypes_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.StatTypesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.StatTypesRecord>>asList(com.houzicore.shared.database.Keys.KEY_statTypes_PRIMARY, com.houzicore.shared.database.Keys.KEY_statTypes_name);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.StatTypes as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.StatTypes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.StatTypes rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.StatTypes(name, null);
	}
}
