/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tasks extends org.jooq.impl.TableImpl<com.houzicore.shared.database.tables.records.TasksRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 787559873;

	/**
	 * The reference instance of <code>Account.tasks</code>
	 */
	public static final com.houzicore.shared.database.tables.Tasks tasks = new com.houzicore.shared.database.tables.Tasks();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.houzicore.shared.database.tables.records.TasksRecord> getRecordType() {
		return com.houzicore.shared.database.tables.records.TasksRecord.class;
	}

	/**
	 * The column <code>Account.tasks.id</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.TasksRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.tasks.name</code>.
	 */
	public final org.jooq.TableField<com.houzicore.shared.database.tables.records.TasksRecord, java.lang.String> name = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>Account.tasks</code> table reference
	 */
	public Tasks() {
		this("tasks", null);
	}

	/**
	 * Create an aliased <code>Account.tasks</code> table reference
	 */
	public Tasks(java.lang.String alias) {
		this(alias, com.houzicore.shared.database.tables.Tasks.tasks);
	}

	private Tasks(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.TasksRecord> aliased) {
		this(alias, aliased, null);
	}

	private Tasks(java.lang.String alias, org.jooq.Table<com.houzicore.shared.database.tables.records.TasksRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.houzicore.shared.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.houzicore.shared.database.tables.records.TasksRecord, java.lang.Integer> getIdentity() {
		return com.houzicore.shared.database.Keys.IDENTITY_tasks;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.TasksRecord> getPrimaryKey() {
		return com.houzicore.shared.database.Keys.KEY_tasks_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.TasksRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.houzicore.shared.database.tables.records.TasksRecord>>asList(com.houzicore.shared.database.Keys.KEY_tasks_PRIMARY, com.houzicore.shared.database.Keys.KEY_tasks_name_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.houzicore.shared.database.tables.Tasks as(java.lang.String alias) {
		return new com.houzicore.shared.database.tables.Tasks(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.houzicore.shared.database.tables.Tasks rename(java.lang.String name) {
		return new com.houzicore.shared.database.tables.Tasks(name, null);
	}
}
