/**
 * This class is generated by jOOQ
 */
package com.houzicore.shared.database;

/**
 * Convenience access to all tables in Account
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table Account.accountClan
	 */
	public static final com.houzicore.shared.database.tables.AccountClan accountClan = com.houzicore.shared.database.tables.AccountClan.accountClan;

	/**
	 * The table Account.accountCoinTransactions
	 */
	public static final com.houzicore.shared.database.tables.AccountCoinTransactions accountCoinTransactions = com.houzicore.shared.database.tables.AccountCoinTransactions.accountCoinTransactions;

	/**
	 * The table Account.accountFriend
	 */
	public static final com.houzicore.shared.database.tables.AccountFriend accountFriend = com.houzicore.shared.database.tables.AccountFriend.accountFriend;

	/**
	 * The table Account.AccountEssenceTransactions
	 */
	public static final com.houzicore.shared.database.tables.AccountEssenceTransactions AccountEssenceTransactions = com.houzicore.shared.database.tables.AccountEssenceTransactions.accountEssenceTransactions;

	/**
	 * The table Account.accountIgnore
	 */
	public static final com.houzicore.shared.database.tables.AccountIgnore accountIgnore = com.houzicore.shared.database.tables.AccountIgnore.accountIgnore;

	/**
	 * The table Account.accountInventory
	 */
	public static final com.houzicore.shared.database.tables.AccountInventory accountInventory = com.houzicore.shared.database.tables.AccountInventory.accountInventory;

	/**
	 * The table Account.accountPolls
	 */
	public static final com.houzicore.shared.database.tables.AccountPolls accountPolls = com.houzicore.shared.database.tables.AccountPolls.accountPolls;

	/**
	 * The table Account.accountPreferences
	 */
	public static final com.houzicore.shared.database.tables.AccountPreferences accountPreferences = com.houzicore.shared.database.tables.AccountPreferences.accountPreferences;

	/**
	 * The table Account.accounts
	 */
	public static final com.houzicore.shared.database.tables.Accounts accounts = com.houzicore.shared.database.tables.Accounts.accounts;

	/**
	 * The table Account.accountStat
	 */
	public static final com.houzicore.shared.database.tables.AccountStat accountStat = com.houzicore.shared.database.tables.AccountStat.accountStat;

	/**
	 * The table Account.accountStats
	 */
	public static final com.houzicore.shared.database.tables.AccountStats accountStats = com.houzicore.shared.database.tables.AccountStats.accountStats;

	/**
	 * The table Account.accountTasks
	 */
	public static final com.houzicore.shared.database.tables.AccountTasks accountTasks = com.houzicore.shared.database.tables.AccountTasks.accountTasks;

	/**
	 * The table Account.accountTransactions
	 */
	public static final com.houzicore.shared.database.tables.AccountTransactions accountTransactions = com.houzicore.shared.database.tables.AccountTransactions.accountTransactions;

	/**
	 * The table Account.activeTournaments
	 */
	public static final com.houzicore.shared.database.tables.ActiveTournaments activeTournaments = com.houzicore.shared.database.tables.ActiveTournaments.activeTournaments;

	/**
	 * The table Account.bonus
	 */
	public static final com.houzicore.shared.database.tables.Bonus bonus = com.houzicore.shared.database.tables.Bonus.bonus;

	/**
	 * The table Account.clanAlliances
	 */
	public static final com.houzicore.shared.database.tables.ClanAlliances clanAlliances = com.houzicore.shared.database.tables.ClanAlliances.clanAlliances;

	/**
	 * The table Account.clanEnemies
	 */
	public static final com.houzicore.shared.database.tables.ClanEnemies clanEnemies = com.houzicore.shared.database.tables.ClanEnemies.clanEnemies;

	/**
	 * VIEW
	 */
	public static final com.houzicore.shared.database.tables.ClanMember clanMember = com.houzicore.shared.database.tables.ClanMember.clanMember;

	/**
	 * The table Account.clans
	 */
	public static final com.houzicore.shared.database.tables.Clans clans = com.houzicore.shared.database.tables.Clans.clans;

	/**
	 * The table Account.clanServer
	 */
	public static final com.houzicore.shared.database.tables.ClanServer clanServer = com.houzicore.shared.database.tables.ClanServer.clanServer;

	/**
	 * The table Account.clanShopItem
	 */
	public static final com.houzicore.shared.database.tables.ClanShopItem clanShopItem = com.houzicore.shared.database.tables.ClanShopItem.clanShopItem;

	/**
	 * The table Account.clanTerritory
	 */
	public static final com.houzicore.shared.database.tables.ClanTerritory clanTerritory = com.houzicore.shared.database.tables.ClanTerritory.clanTerritory;

	/**
	 * The table Account.eloRating
	 */
	public static final com.houzicore.shared.database.tables.EloRating eloRating = com.houzicore.shared.database.tables.EloRating.eloRating;

	/**
	 * The table Account.fieldBlock
	 */
	public static final com.houzicore.shared.database.tables.FieldBlock fieldBlock = com.houzicore.shared.database.tables.FieldBlock.fieldBlock;

	/**
	 * The table Account.fieldMonster
	 */
	public static final com.houzicore.shared.database.tables.FieldMonster fieldMonster = com.houzicore.shared.database.tables.FieldMonster.fieldMonster;

	/**
	 * The table Account.fieldOre
	 */
	public static final com.houzicore.shared.database.tables.FieldOre fieldOre = com.houzicore.shared.database.tables.FieldOre.fieldOre;

	/**
	 * The table Account.itemCategories
	 */
	public static final com.houzicore.shared.database.tables.ItemCategories itemCategories = com.houzicore.shared.database.tables.ItemCategories.itemCategories;

	/**
	 * The table Account.items
	 */
	public static final com.houzicore.shared.database.tables.Items items = com.houzicore.shared.database.tables.Items.items;

	/**
	 * The table Account.mail
	 */
	public static final com.houzicore.shared.database.tables.Mail mail = com.houzicore.shared.database.tables.Mail.mail;

	/**
	 * The table Account.mailbox
	 */
	public static final com.houzicore.shared.database.tables.Mailbox mailbox = com.houzicore.shared.database.tables.Mailbox.mailbox;

	/**
	 * The table Account.npcs
	 */
	public static final com.houzicore.shared.database.tables.Npcs npcs = com.houzicore.shared.database.tables.Npcs.npcs;

	/**
	 * The table Account.playerMap
	 */
	public static final com.houzicore.shared.database.tables.PlayerMap playerMap = com.houzicore.shared.database.tables.PlayerMap.playerMap;

	/**
	 * The table Account.polls
	 */
	public static final com.houzicore.shared.database.tables.Polls polls = com.houzicore.shared.database.tables.Polls.polls;

	/**
	 * The table Account.rankBenefits
	 */
	public static final com.houzicore.shared.database.tables.RankBenefits rankBenefits = com.houzicore.shared.database.tables.RankBenefits.rankBenefits;

	/**
	 * The table Account.serverPassword
	 */
	public static final com.houzicore.shared.database.tables.ServerPassword serverPassword = com.houzicore.shared.database.tables.ServerPassword.serverPassword;

	/**
	 * The table Account.spawns
	 */
	public static final com.houzicore.shared.database.tables.Spawns spawns = com.houzicore.shared.database.tables.Spawns.spawns;

	/**
	 * The table Account.statEvents
	 */
	public static final com.houzicore.shared.database.tables.StatEvents statEvents = com.houzicore.shared.database.tables.StatEvents.statEvents;

	/**
	 * The table Account.stats
	 */
	public static final com.houzicore.shared.database.tables.Stats stats = com.houzicore.shared.database.tables.Stats.stats;

	/**
	 * Stores a reference of the various types of statistics and their associated stat type IDs.
	 */
	public static final com.houzicore.shared.database.tables.StatTypes statTypes = com.houzicore.shared.database.tables.StatTypes.statTypes;

	/**
	 * The table Account.tasks
	 */
	public static final com.houzicore.shared.database.tables.Tasks tasks = com.houzicore.shared.database.tables.Tasks.tasks;

	/**
	 * The table Account.TournamentLB
	 */
	public static final com.houzicore.shared.database.tables.TournamentLB TournamentLB = com.houzicore.shared.database.tables.TournamentLB.TournamentLB;

	/**
	 * The table Account.transactions
	 */
	public static final com.houzicore.shared.database.tables.Transactions transactions = com.houzicore.shared.database.tables.Transactions.transactions;
}
