name: MapBuilder
version: 1.0.0
main: com.houzicore.mapbuilder.MapBuilderPlugin
api-version: '26.1.2'
authors: [HouziCore]
description: A tool for builders to easily create and export minigame map configurations.

commands:
  mapbuilder:
    description: Core command for MapBuilder plugin
    aliases: [mb]
    permission: mapbuilder.admin
    usage: /mapbuilder <create|export|cancel>
