name: KitTester
version: '1.0-SNAPSHOT'
main: com.houzicore.kittester.KitTester
api-version: '26.1.2'
depend: [Shared, Arcade]
description: A plugin to test kits and perks before importing them to Arcade

commands:
  testkit:
    description: Opens the Kit Tester menu or gives a test item
    usage: /testkit
