package com.houzicore.extension.util.constant;

import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;

public enum ModuleName {

    MODULE,

    COMMAND,
    COMMAND_AFK,
    COMMAND_ANON,
    COMMAND_BALL,
    COMMAND_BAN,
    COMMAND_BANLIST,
    COMMAND_BROADCAST,
    COMMAND_CHATCOLOR,
    COMMAND_CHATSETTING,
    COMMAND_CLEARCHAT,
    COMMAND_CLEARMAIL,
    COMMAND_COIN,
    COMMAND_DELETEMESSAGE,
    COMMAND_DICE,
    COMMAND_DO,
    COMMAND_EMIT,
    COMMAND_FLECTONEPULSE,
    COMMAND_GEOLOCATE,
    COMMAND_HELPER,
    COMMAND_IGNORE,
    COMMAND_IGNORELIST,
    COMMAND_KICK,
    COMMAND_MAIL,
    COMMAND_MAINTENANCE,
    COMMAND_ME,
    COMMAND_MUTE,
    COMMAND_MUTELIST,
    COMMAND_NICKNAME,
    COMMAND_ONLINE,
    COMMAND_PING,
    COMMAND_POLL,
    COMMAND_REPLY,
    COMMAND_ROCKPAPERSCISSORS,
    COMMAND_SPRITE,
    COMMAND_SPY,
    COMMAND_STREAM,
    COMMAND_SYMBOL,
    COMMAND_TELL,
    COMMAND_TICTACTOE,
    COMMAND_TOPONLINE,
    COMMAND_TRANSLATETO,
    COMMAND_TRY,
    COMMAND_UNBAN,
    COMMAND_UNMUTE,
    COMMAND_UNWARN,
    COMMAND_WARN,
    COMMAND_WARNLIST,

    INTEGRATION,
    INTEGRATION_ADVANCEDBAN,
    INTEGRATION_CMI,
    INTEGRATION_DEEPL,
    INTEGRATION_DISCORD,
    INTEGRATION_FLOODGATE,
    INTEGRATION_GEYSER,
    INTEGRATION_INTERACTIVECHAT,
    INTEGRATION_ITEMSADDER,
    INTEGRATION_LIBERTYBANS,
    INTEGRATION_LITEBANS,
    INTEGRATION_LUCKPERMS,
    INTEGRATION_MAINTENANCE,
    INTEGRATION_MINIMOTD,
    INTEGRATION_MINIPLACEHOLDERS,
    INTEGRATION_MOTD,
    INTEGRATION_PLACEHOLDERAPI,
    INTEGRATION_PLASMOVOICE,
    INTEGRATION_SIMPLEVOICE,
    INTEGRATION_SKINSRESTORER,
    INTEGRATION_SUPERVANISH,
    INTEGRATION_TAB,
    INTEGRATION_TELEGRAM,
    INTEGRATION_TRITON,
    INTEGRATION_TWITCH,
    INTEGRATION_VAULT,
    INTEGRATION_YANDEX,

    MESSAGE,
    MESSAGE_AFK,
    MESSAGE_ANVIL,
    MESSAGE_AUTO,
    MESSAGE_BOOK,
    MESSAGE_BOSSBAR,
    MESSAGE_BRAND,
    MESSAGE_BUBBLE,
    MESSAGE_CHAT,
    MESSAGE_FORMAT,
    MESSAGE_FORMAT_ANIMATION,
    MESSAGE_FORMAT_CONDITION,
    MESSAGE_FORMAT_FCOLOR,
    MESSAGE_FORMAT_FIXATION,
    MESSAGE_FORMAT_MENTION,
    MESSAGE_FORMAT_MODERATION,
    MESSAGE_FORMAT_MODERATION_CAPS,
    MESSAGE_FORMAT_MODERATION_DELETE,
    MESSAGE_FORMAT_MODERATION_FLOOD,
    MESSAGE_FORMAT_MODERATION_NEWBIE,
    MESSAGE_FORMAT_MODERATION_SWEAR,
    MESSAGE_FORMAT_NAMES,
    MESSAGE_FORMAT_OBJECT,
    MESSAGE_FORMAT_QUESTIONANSWER,
    MESSAGE_FORMAT_REPLACEMENT,
    MESSAGE_FORMAT_SCOREBOARD,
    MESSAGE_FORMAT_TRANSLATE,
    MESSAGE_FORMAT_WORLD,
    MESSAGE_GREETING,
    MESSAGE_JOIN,
    MESSAGE_OBJECTIVE,
    MESSAGE_OBJECTIVE_BELOWNAME,
    MESSAGE_OBJECTIVE_TABNAME,
    MESSAGE_QUIT,
    MESSAGE_RIGHTCLICK,
    MESSAGE_SIDEBAR,
    MESSAGE_SIGN,
    MESSAGE_STATUS,
    MESSAGE_STATUS_ICON,
    MESSAGE_STATUS_MOTD,
    MESSAGE_STATUS_PLAYERS,
    MESSAGE_STATUS_VERSION,
    MESSAGE_TAB,
    MESSAGE_TAB_FOOTER,
    MESSAGE_TAB_HEADER,
    MESSAGE_TAB_PLAYERLISTNAME,
    MESSAGE_UPDATE,
    MESSAGE_VANILLA,

    ERROR,

    SERVER_ENABLE,
    SERVER_DISABLE,

    // only for invalidation cache
    SYSTEM_COOLDOWN,
    SYSTEM_ONLINE,
    SYSTEM_OFFLINE,
    SYSTEM_BAN,
    SYSTEM_MUTE,
    SYSTEM_WARN;

    private static final Map<String, ModuleName> ENUM_BY_PROXY_KEY = Arrays.stream(ModuleName.values())
            .collect(Collectors.toUnmodifiableMap(
                    ModuleName::toProxyTag,
                    messageType -> messageType
            ));

    public static ModuleName fromProxyString(String string) {
        if (string == null || string.isEmpty()) return null;

        return ENUM_BY_PROXY_KEY.get(string);
    }

    public String toProxyTag() {
        return "HouziExtension:" + this.name();
    }

}
